In [1]:
import pandas as pd
df = pd.read_csv("star_classification.csv")
df.rename(columns={'class': 'classification'}, inplace=True)

In [2]:
df

,obj_ID,alpha,delta,u,g,r,i,z,run_ID,rerun_ID,cam_col,field_ID,spec_obj_ID,classification,redshift,plate,MJD,fiber_ID
0,1.237661e+18,135.689107,32.494632,23.87882,22.27530,20.39501,19.16573,18.79371,3606,301,2,79,6.543777e+18,GALAXY,0.634794,5812,56354,171
1,1.237665e+18,144.826101,31.274185,24.77759,22.83188,22.58444,21.16812,21.61427,4518,301,5,119,1.176014e+19,GALAXY,0.779136,10445,58158,427
2,1.237661e+18,142.188790,35.582444,25.26307,22.66389,20.60976,19.34857,18.94827,3606,301,2,120,5.152200e+18,GALAXY,0.644195,4576,55592,299
3,1.237663e+18,338.741038,-0.402828,22.13682,23.77656,21.61162,20.50454,19.25010,4192,301,3,214,1.030107e+19,GALAXY,0.932346,9149,58039,775
4,1.237680e+18,345.282593,21.183866,19.43718,17.58028,16.49747,15.97711,15.54461,8102,301,3,137,6.891865e+18,GALAXY,0.116123,6121,56187,842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1.237679e+18,39.620709,-2.594074,22.16759,22.97586,21.90404,21.30548,20.73569,7778,301,2,581,1.055431e+19,GALAXY,0.000000,9374,57749,438
99996,1.237679e+18,29.493819,19.798874,22.69118,22.38628,20.45003,19.75759,19.41526,7917,301,1,289,8.586351e+18,GALAXY,0.404895,7626,56934,866
99997,1.237668e+18,224.587407,15.700707,21.16916,19.26997,18.20428,17.69034,17.35221,5314,301,4,308,3.112008e+18,GALAXY,0.143366,2764,54535,74
99998,1.237661e+18,212.268621,46.660365,25.35039,21.63757,19.91386,19.07254,18.62482,3650,301,4,131,7.601080e+18,GALAXY,0.455040,6751,56368,470
99999,1.237661e+18,196.896053,49.464643,22.62171,21.79745,20.60115,20.00959,19.28075,3650,301,4,60,8.343152e+18,GALAXY,0.542944,7410,57104,851

In [3]:
# Ok lets get rid of all the meaningless columns
# IDs and the location of the object in the sky doesn't correlate to what the object is - there are galaxies in every direction.
# Therefore, let's only take in the intensity (light) data and the redshift (distance) data.
df = df[["classification", "u", "g", "r", "i", "z", "redshift"]]
df

,classification,u,g,r,i,z,redshift
0,GALAXY,23.87882,22.27530,20.39501,19.16573,18.79371,0.634794
1,GALAXY,24.77759,22.83188,22.58444,21.16812,21.61427,0.779136
2,GALAXY,25.26307,22.66389,20.60976,19.34857,18.94827,0.644195
3,GALAXY,22.13682,23.77656,21.61162,20.50454,19.25010,0.932346
4,GALAXY,19.43718,17.58028,16.49747,15.97711,15.54461,0.116123
...,...,...,...,...,...,...,...
99995,GALAXY,22.16759,22.97586,21.90404,21.30548,20.73569,0.000000
99996,GALAXY,22.69118,22.38628,20.45003,19.75759,19.41526,0.404895
99997,GALAXY,21.16916,19.26997,18.20428,17.69034,17.35221,0.143366
99998,GALAXY,25.35039,21.63757,19.91386,19.07254,18.62482,0.455040
99999,GALAXY,22.62171,21.79745,20.60115,20.00959,19.28075,0.542944

In [4]:
df.describe()

,u,g,r,i,z,redshift
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,21.980468,20.531387,19.645762,19.084854,18.668810,0.576661
std,31.769291,31.750292,1.854760,1.757895,31.728152,0.730707
min,-9999.000000,-9999.000000,9.822070,9.469903,-9999.000000,-0.009971
25%,20.352353,18.965230,18.135828,17.732285,17.460677,0.054517
50%,22.179135,21.099835,20.125290,19.405145,19.004595,0.424173
75%,23.687440,22.123767,21.044785,20.396495,19.921120,0.704154
max,32.781390,31.602240,29.571860,32.141470,29.383740,7.011245

In [5]:
df = df.query("u >= 0")
df

,classification,u,g,r,i,z,redshift
0,GALAXY,23.87882,22.27530,20.39501,19.16573,18.79371,0.634794
1,GALAXY,24.77759,22.83188,22.58444,21.16812,21.61427,0.779136
2,GALAXY,25.26307,22.66389,20.60976,19.34857,18.94827,0.644195
3,GALAXY,22.13682,23.77656,21.61162,20.50454,19.25010,0.932346
4,GALAXY,19.43718,17.58028,16.49747,15.97711,15.54461,0.116123
...,...,...,...,...,...,...,...
99995,GALAXY,22.16759,22.97586,21.90404,21.30548,20.73569,0.000000
99996,GALAXY,22.69118,22.38628,20.45003,19.75759,19.41526,0.404895
99997,GALAXY,21.16916,19.26997,18.20428,17.69034,17.35221,0.143366
99998,GALAXY,25.35039,21.63757,19.91386,19.07254,18.62482,0.455040
99999,GALAXY,22.62171,21.79745,20.60115,20.00959,19.28075,0.542944

In [6]:
df["classification"].value_counts()

classification
GALAXY    59445
STAR      21593
QSO       18961
Name: count, dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 99999 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   classification  99999 non-null  object
 1   u               99999 non-null  float64
 2   g               99999 non-null  float64
 3   r               99999 non-null  float64
 4   i               99999 non-null  float64
 5   z               99999 non-null  float64
 6   redshift        99999 non-null  float64
dtypes: float64(6), object(1)
memory usage: 6.1+ MB

In [8]:
df = df[:10000]
df

,classification,u,g,r,i,z,redshift
0,GALAXY,23.87882,22.27530,20.39501,19.16573,18.79371,0.634794
1,GALAXY,24.77759,22.83188,22.58444,21.16812,21.61427,0.779136
2,GALAXY,25.26307,22.66389,20.60976,19.34857,18.94827,0.644195
3,GALAXY,22.13682,23.77656,21.61162,20.50454,19.25010,0.932346
4,GALAXY,19.43718,17.58028,16.49747,15.97711,15.54461,0.116123
...,...,...,...,...,...,...,...
9995,STAR,23.76142,21.60551,20.18169,18.82800,17.97066,0.000021
9996,GALAXY,25.28108,23.24951,22.21676,21.77299,21.70472,0.461456
9997,STAR,19.30690,17.86614,17.28298,17.05059,16.93477,-0.000026
9998,STAR,22.98510,22.00351,21.82306,21.84666,21.60912,-0.001457
9999,STAR,20.52470,19.41211,18.94506,18.71993,18.59895,-0.000204

In [9]:
df["classification"].value_counts()

classification
GALAXY    6091
STAR      1994
QSO       1915
Name: count, dtype: int64

In [10]:
df.describe()

,u,g,r,i,z,redshift
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,22.092181,20.632011,19.647712,19.093144,18.782311,0.578152
std,2.240051,2.017495,1.840296,1.748652,1.768755,0.738068
min,12.262400,10.511390,10.068540,11.299560,10.225510,-0.006863
25%,20.393127,19.019950,18.170388,17.751263,17.477602,0.067309
50%,22.161055,21.044670,20.111605,19.421320,19.019795,0.396535
75%,23.699983,22.104915,21.031577,20.414717,19.932910,0.697875
max,29.199010,28.903200,27.397090,30.154600,26.427790,7.011245

In [11]:
df = df.query("redshift > 0")
df.describe()

,u,g,r,i,z,redshift
count,8682.000000,8682.000000,8682.000000,8682.000000,8682.000000,8.682000e+03
mean,22.225972,20.772791,19.735482,19.153929,18.823513,6.659694e-01
std,2.185802,1.960106,1.801818,1.723656,1.748704,7.542762e-01
min,12.262400,10.511390,10.068540,11.299560,10.225510,1.762243e-07
25%,20.549148,19.290290,18.368627,17.864705,17.566637,1.475338e-01
50%,22.274315,21.189500,20.195645,19.469370,19.059045,4.862005e-01
75%,23.779365,22.177515,21.077950,20.439547,19.936653,7.788358e-01
max,29.199010,27.264660,27.397090,30.154600,26.427790,7.011245e+00

In [12]:
# Let's test a simple support vector machine to see if it can work.

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split, GridSearchCV

X = df.iloc[:, 1:].copy().to_numpy()
y = df.iloc[:, 0].copy().to_numpy()

In [13]:
X = (X - np.average(X, axis=0)) / np.std(X, axis=0)

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [15]:
clf = SVC(C=1.0, kernel='linear') # linear seems to be doing better than rbf?
clf.fit(X_train, y_train)

SVC(kernel='linear')

In [16]:
confusion_matrix(y_test, clf.predict(X_test), normalize="true")

array([[0.9768595 , 0.0107438 , 0.01239669],
       [0.13853904, 0.86146096, 0.        ],
       [0.03846154, 0.        , 0.96153846]])